### ISSUE TITLE
platformio gives warnings and errors

### ISSUE THREAD

**Issue by Phoenix3232** [gasagna/A76XX#8]
Hello. I added a library to my project esp 32 in the platformIO and when building the project it gives a lot of warnings and an error.

<img width="835" alt="image" src="https://github.com/user-attachments/assets/7c116291-0eb8-48b3-9a8e-1b3e41513081">

<img width="408" alt="image" src="https://github.com/user-attachments/assets/2416bfac-0be8-455c-ba22-164d5fc4f296">

**Comment by gasagna** [comment]
Hi @Phoenix3232, 

thanks for trying out my library.

Unfortunately, I am not sure how to help here. These warnings look more of a compiler flags thing, rather than a genuine problem with the library's code. 

Have you made any progress on this?

**Comment by Phoenix3232** [comment]
@gasagna 
Yes, I solved the problem.
In the first case, there was a conflict with the tinygsm library.
In the second case, I removed your annotations after #endif
The compiler complains about them.

**Comment by Phoenix3232** [comment]
Have you considered making the library capable of downloading updates for Arduino/esp32 (OTA)?

**Comment by gasagna** [comment]
Hi @Phoenix3232, note really. Is this a functionality of the SIMCOM module?

**Comment by Phoenix3232** [comment]
> Привет@Phoenix3232, заметьте, действительно. Это функционал модуля SIMCOM?

<img width="764" alt="image" src="https://github.com/user-attachments/assets/896fe5d9-04f7-4c81-87c4-bc9b059e39c8">

I mean to implement the Client class through your library. So that you can update the firmware of the esp 32 through the "esp32 firmware OTA".

**Comment by gasagna** [comment]
Hi @Phoenix3232 , there are several command for OTA in the simcom documentation (see chapters 22 and 23 of the v1.09 AT command manual), but this is beyond my expertise. 

However, there should be enough functionality in the library that you can create a wrapper yourself. The first step would be to implement all commands available (see the "commands" folder), and then create a client class that manages everything.

**Comment by Phoenix3232** [comment]
> Hi @Phoenix3232 , there are several command for OTA in the simcom documentation (see chapters 22 and 23 of the v1.09 AT command manual), but this is beyond my expertise.
> 
> However, there should be enough functionality in the library that you can create a wrapper yourself. The first step would be to implement all commands available (see the "commands" folder), and then create a client class that manages everything.

I'm talking about over-the-air update of esp32, not modem.
For over-the-air update of esp32 there is a library Update, to which you need to pass the implementation of the Client class.
For tinygsm this is the class TinygsmClient.
Have you considered making an implementation of the Client class based on your library?

**Comment by gasagna** [comment]
Not really. The goal of this library is to expose the built-in functionality that the SIMCOM module provides. It might be possible to define a Client class that uses this functionality, but I have not investigated this very much and I do not think it makes sense given the purpose of the library.
